### ISSUE TITLE
Unsure how to use this package with custom FRI version?

### ISSUE THREAD

**Issue by PeterMitrano** [lbr-stack/fri_vendor#2]
I'm trying to use FRI 1.11, which I have the Zip for. I tried to use this command

```
colcon build --cmake-args -DFRI_CLIENT_VERSION=1.11
```
But it failed with:
```
error: pathspec 'fri-1.11' did not match any file(s) known to git
CMake Error at /home/peter/lbr_fri_ros2_stack_ws/build/fri_vendor/FRIClient-prefix/tmp/FRIClient-gitupdate.cmake:175 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"

```

I'm not sure where or how I'm supposed to tell it about my FRI zip? where does it go? does it have to be named something special?

Thanks!

**Comment by mhubii** [comment]
hi @PeterMitrano , sorry, seeing this issue very late!

The `fri_vendor` package fetches the `fri` via CMake from https://github.com/lbr-stack/fri in this line https://github.com/lbr-stack/fri_vendor/blob/f2877ce9b220207670164e184b1fa6a1b3947104/CMakeLists.txt#L16

If you are planning to use `fri-1.11`, you'll have to follow the instructions here: https://github.com/lbr-stack/fri#contributing, I created an issue for you here https://github.com/lbr-stack/fri/issues/19 and am closing this one.

Hope this hint still finds you in time. Please feel free to tag me in future issues.

**Comment by mhubii** [comment]
Closed in favor for https://github.com/lbr-stack/fri/issues/19
